-- Owner-only application access.
create or replace function public.is_system_owner() returns boolean language sql stable security definer set search_path=public as $$ select lower(coalesce(auth.email(),''))='shehab.star8@gmail.com'; $$;
revoke all on function public.is_system_owner() from public,anon,authenticated;
create or replace function public.require_current_user() returns uuid language plpgsql security definer set search_path=public as $$ declare v_uid uuid:=auth.uid(); v_email text:=lower(coalesce(auth.email(),'')); begin if v_uid is null then raise exception 'Authentication required'; end if; if v_email<>'shehab.star8@gmail.com' then raise exception 'User is not authorized for this system'; end if; return v_uid; end; $$;
do $$ begin
if to_regprocedure('public.get_template_management_data(uuid)') is not null then execute 'alter function public.get_template_management_data(uuid) rename to get_template_management_data_internal_owner_gate'; end if;
if to_regprocedure('public.get_template_fields(uuid)') is not null then execute 'alter function public.get_template_fields(uuid) rename to get_template_fields_internal_owner_gate'; end if;
if to_regprocedure('public.get_document_creation_options()') is not null then execute 'alter function public.get_document_creation_options() rename to get_document_creation_options_internal_owner_gate'; end if;
if to_regprocedure('public.preview_document_number(uuid,text,text,text,text,text,text)') is not null then execute 'alter function public.preview_document_number(uuid,text,text,text,text,text,text) rename to preview_document_number_internal_owner_gate'; end if;
if to_regprocedure('public.preview_document_number(uuid,text,text,text,text)') is not null then execute 'alter function public.preview_document_number(uuid,text,text,text,text) rename to preview_document_number_internal_owner_gate_simple'; end if;
if to_regprocedure('public.create_document_next(uuid,text,text,text,text,uuid)') is not null then execute 'alter function public.create_document_next(uuid,text,text,text,text,uuid) rename to create_document_next_internal_owner_gate'; end if;
end $$;
create or replace function public.get_template_management_data(p_project_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$ begin perform public.require_current_user(); return public.get_template_management_data_internal_owner_gate(p_project_id); end; $$;
create or replace function public.get_template_fields(p_template_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$ begin perform public.require_current_user(); return public.get_template_fields_internal_owner_gate(p_template_id); end; $$;
create or replace function public.get_document_creation_options() returns jsonb language plpgsql security definer set search_path=public as $$ begin perform public.require_current_user(); return public.get_document_creation_options_internal_owner_gate(); end; $$;
create or replace function public.preview_document_number(p_project_id uuid,p_document_type_code text,p_network_code text,p_zone text,p_from_code text,p_to_code text,p_revision text) returns text language plpgsql security definer set search_path=public as $$ begin perform public.require_current_user(); return public.preview_document_number_internal_owner_gate(p_project_id,p_document_type_code,p_network_code,p_zone,p_from_code,p_to_code,p_revision); end; $$;
create or replace function public.preview_document_number(p_project_id uuid,p_document_type_code text,p_network_code text,p_zone text,p_revision text) returns text language plpgsql security definer set search_path=public as $$ begin perform public.require_current_user(); return public.preview_document_number_internal_owner_gate_simple(p_project_id,p_document_type_code,p_network_code,p_zone,p_revision); end; $$;
create or replace function public.create_document_next(p_project_id uuid,p_document_type_code text,p_network_code text,p_zone text,p_description text,p_created_by uuid) returns uuid language plpgsql security definer set search_path=public as $$ begin perform public.require_current_user(); return public.create_document_next_internal_owner_gate(p_project_id,p_document_type_code,p_network_code,p_zone,p_description,p_created_by); end; $$;
do $$ declare r record; begin for r in select c.relname table_name from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' loop execute format('alter table public.%I enable row level security',r.table_name); execute format('drop policy if exists "owner_only_access" on public.%I',r.table_name); execute format('create policy "owner_only_access" on public.%I for all to authenticated using (public.is_system_owner()) with check (public.is_system_owner())',r.table_name); execute format('revoke all on table public.%I from public,anon',r.table_name); execute format('grant select,insert,update,delete,references,trigger on table public.%I to authenticated',r.table_name); end loop; end $$;
revoke all on all sequences in schema public from public,anon;
grant usage,select,update on all sequences in schema public to authenticated;
revoke all on all functions in schema public from public,anon,authenticated;
grant execute on function public.get_template_management_data(uuid) to authenticated;
grant execute on function public.get_template_fields(uuid) to authenticated;
grant execute on function public.get_document_creation_options() to authenticated;
grant execute on function public.preview_document_number(uuid,text,text,text,text,text,text) to authenticated;
grant execute on function public.preview_document_number(uuid,text,text,text,text) to authenticated;
grant execute on function public.create_document_next(uuid,text,text,text,text,uuid) to authenticated;
grant execute on function public.create_document_next(uuid,text,text,text,text,text,text,text,uuid) to authenticated;
grant execute on function public.save_document_form_data(uuid,uuid,jsonb,jsonb) to authenticated;
grant execute on function public.upsert_template_record(uuid,uuid,uuid,text,text,text,text) to authenticated;
grant execute on function public.get_current_user_access() to authenticated;
grant execute on function public.require_current_user() to authenticated;
drop policy if exists "template_delete_from_app" on storage.objects;
drop policy if exists "template_select_from_app" on storage.objects;
drop policy if exists "template_upload_from_app" on storage.objects;
create policy "template_select_owner_only" on storage.objects for select to authenticated using (bucket_id='document-templates' and public.is_system_owner());
create policy "template_upload_owner_only" on storage.objects for insert to authenticated with check (bucket_id='document-templates' and public.is_system_owner());
create policy "template_update_owner_only" on storage.objects for update to authenticated using (bucket_id='document-templates' and public.is_system_owner()) with check (bucket_id='document-templates' and public.is_system_owner());
create policy "template_delete_owner_only" on storage.objects for delete to authenticated using (bucket_id='document-templates' and public.is_system_owner());