"use client";

import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
const PROJECT_ID="ee505976-e729-4771-a0e7-4de2a8a32596";
const DOC_TYPES=["WIR","SHD","MIR","MIA","DS","DT"];
type T={template_id:string;template_name:string;template_version:string|null;template_file_path:string|null;is_active:boolean;document_type_code:string;network_code:string;network_name:string};
type N={network_id:string;network_code:string;network_name:string}; type D={document_type_id:string;type_code:string;type_name:string}; type P={project_id:string;project_code:string;project_name:string};

export default function Home(){
 const [page,setPage]=useState("Dashboard"),[project,setProject]=useState<P|null>(null),[templates,setTemplates]=useState<T[]>([]),[networks,setNetworks]=useState<N[]>([]),[types,setTypes]=useState<D[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const [c,setC]=useState({typeId:"",networkId:"",zone:"",from:"NHC",to:"DAR",revision:"0"}),[preview,setPreview]=useState("");
 async function load(){setBusy(true);const {data,error}=await supabase.rpc("get_template_management_data",{p_project_id:PROJECT_ID});if(error)setMsg(error.message);else{const x=data as any;setProject(x.project);setTypes(x.document_types||[]);setNetworks(x.networks||[]);setTemplates(x.templates||[])}setBusy(false)}
 useEffect(()=>{load()},[]); const tc=types.find(x=>x.document_type_id===c.typeId)?.type_code||""; const nc=networks.find(x=>x.network_id===c.networkId)?.network_code||"";
 const nets=networks.filter(x=>tc!=="DT"?x.network_code!=="IPC":true); const activeForm=templates.find(x=>x.is_active&&x.document_type_code===tc&&x.network_code===nc);
 async function generate(){setMsg("");if(!tc||!nc||!c.zone.trim()){setMsg("Select Document Type, Network and Zone.");return}setBusy(true);const {data,error}=await supabase.rpc("preview_document_number",{p_project_id:PROJECT_ID,p_document_type_code:tc,p_network_code:nc,p_zone:c.zone.trim(),p_from_code:c.from.trim(),p_to_code:c.to.trim(),p_revision:c.revision.trim()||"0"});if(error)setMsg(error.message);else setPreview(String(data));setBusy(false)}
 return <main className="min-h-screen bg-slate-100 text-slate-900"><div className="flex min-h-screen"><aside className="w-64 bg-slate-900 text-white p-5"><h1 className="text-xl font-bold">DOCUMENT CONTROL</h1><p className="text-xs text-slate-400 mb-8">Jeddah Heights Infrastructure</p>{["Dashboard","Create Document","Central Search","Revision Control","Reports","Templates","Users & Security","Audit Log"].map(x=><button key={x} onClick={()=>setPage(x)} className={`w-full text-left px-4 py-3 rounded-lg mb-2 ${page===x?"bg-blue-600":"hover:bg-slate-800"}`}>{x}</button>)}</aside><section className="flex-1 p-8"><h2 className="text-3xl font-bold mb-1">{page}</h2><p className="text-slate-500 mb-8">{project?.project_name||"Integrated Document Control System"}</p>{page==="Create Document"?<Create c={c} setC={setC} tc={tc} nc={nc} networks={nets} types={types} form={activeForm} preview={preview} busy={busy} msg={msg} generate={generate}/>:page==="Templates"?<Templates templates={templates}/>:<Dashboard templates={templates} types={types} networks={networks}/>}</section></div></main>
}
function Create({c,setC,tc,nc,networks,types,form,preview,busy,msg,generate}:any){const set=(k:string,v:string)=>{setC({...c,[k]:v});setPreview("")};return <div className="space-y-6"><div className="bg-white rounded-xl shadow-sm p-6"><h3 className="text-xl font-semibold">Create Document</h3><p className="text-sm text-slate-500 mt-1 mb-6">Generate is preview-only. The serial is consumed only when the document is actually created.</p><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Sel label="Document Type" value={c.typeId} onChange={(v:string)=>set("typeId",v)} options={types.map((x:D)=>({value:x.document_type_id,label:`${x.type_code} — ${x.type_name}`}))}/><Sel label="Network" value={c.networkId} onChange={(v:string)=>set("networkId",v)} options={networks.map((x:N)=>({value:x.network_id,label:`${x.network_code} — ${x.network_name}`}))}/><Inp label="Zone" value={c.zone} onChange={(v:string)=>set("zone",v)} placeholder="V4"/><Inp label="From" value={c.from} onChange={(v:string)=>set("from",v.toUpperCase())} placeholder="NHC"/><Inp label="To" value={c.to} onChange={(v:string)=>set("to",v.toUpperCase())} placeholder="DAR"/><Inp label="Revision" value={c.revision} onChange={(v:string)=>set("revision",v)} placeholder="0"/></div><button disabled={busy} onClick={generate} className="mt-5 px-5 py-2.5 rounded-lg bg-blue-600 text-white">{busy?"Generating...":"Generate Number"}</button>{msg&&<p className="mt-4 text-sm text-red-600">{msg}</p>}</div><div className="bg-white rounded-xl shadow-sm p-6"><h3 className="font-semibold">Document Number Preview</h3>{preview?<div className="mt-4 bg-slate-900 text-white rounded-lg p-5 font-mono text-xl">{preview}</div>:<p className="mt-4 text-slate-500">No number generated.</p>}<div className="mt-5 border-t pt-5"><b>Active Form:</b> {form?`${form.template_name} (v${form.template_version||"—"})`:tc&&nc?`No active form configured for ${tc} / ${nc}`:"Select Type and Network"}</div></div></div>}
function Templates({templates}:{templates:T[]}){return <div className="bg-white rounded-xl shadow-sm p-6"><h3 className="text-xl font-semibold mb-5">Project Templates</h3><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-3">Type</th><th>Network</th><th>Template</th><th>Version</th><th>Status</th></tr></thead><tbody>{templates.map(x=><tr key={x.template_id} className="border-b"><td className="py-3 font-semibold">{x.document_type_code}</td><td>{x.network_code}</td><td>{x.template_name}</td><td>{x.template_version||"—"}</td><td>{x.is_active?"Active":"Inactive"}</td></tr>)}</tbody></table></div>}
function Dashboard({templates,types,networks}:{templates:T[];types:D[];networks:N[]}){return <><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5 mb-8"><Stat title="Total Templates" value={String(templates.length)}/><Stat title="Active Templates" value={String(templates.filter(x=>x.is_active).length)}/><Stat title="Document Types" value={String(types.length)}/><Stat title="Networks" value={String(networks.length)}/></div><div className="bg-white rounded-xl shadow-sm p-6"><h3 className="font-semibold mb-5">Document Types</h3><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">{DOC_TYPES.map(x=><div key={x} className="border rounded-xl p-5 text-center"><div className="text-2xl font-bold text-blue-600">{x}</div><div className="text-sm text-slate-500 mt-2">{templates.filter(t=>t.document_type_code===x).length} Templates</div></div>)}</div></div></>}
function Sel({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <label className="text-sm font-medium">{label}<select className="mt-1 w-full border rounded-lg px-3 py-2 bg-white" value={value} onChange={e=>onChange(e.target.value)}><option value="">Select...</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
function Inp({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="text-sm font-medium">{label}<input className="mt-1 w-full border rounded-lg px-3 py-2" value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function Stat({title,value}:{title:string;value:string}){return <div className="bg-white rounded-xl shadow-sm p-6"><p className="text-sm text-slate-500">{title}</p><p className="text-3xl font-bold mt-2">{value}</p></div>}
